name: Validate Application Approval

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check approval status
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            const approved = reviews.data.filter(review => review.state === 'APPROVED').length >= 2;
            if (!approved) {
              console.log('Approval validation failed');
              process.exit(1);
            }
