name: Automerge Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  automerge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR status and merge
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            const approvedReviews = reviews.data.filter(review => review.state === 'APPROVED').length;
            if (pr.data.mergeable && approvedReviews >= 2) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                merge_method: 'merge'
              });
            } else {
              console.log('PR not mergeable or insufficient approvals');
              process.exit(1);
            }
