name: Check Application Changes

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # 获取足够的历史记录以比较更改

      - name: Check for changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q 'path/to/application/files'; then
            echo "Application changes detected"
          else
            echo "No application changes detected"
            exit 1
          fi
