name: Flow Validator

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  validate-flow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate flow
        run: |
          if [ "${{ github.actor }}" == "filplus-bot" ] || grep -q 'submitted' path/to/application/file; then
            echo "Flow validation passed"
          else
            echo "Flow validation failed"
            exit 1
          fi
