name: Convert Issue To Pull Request

on:
  issues:
    types:
      - opened

jobs:
  convert-issue-to-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Convert issue #${{ github.event.issue.number }} to PR'
          body: 'This PR is created from issue #${{ github.event.issue.number }}'
          branch: 'issue-${{ github.event.issue.number }}'
          commit-message: 'Create PR from issue #${{ github.event.issue.number }}'
