name: Update PR from Issue Modification

on:
  issues:
    types:
      - edited

jobs:
  update-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = ${{ github.event.issue.number }};
            // 假设PR标题包含Issue编号
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            const targetPr = prs.data.find(pr => pr.title.includes(`#${issueNumber}`));
            if (targetPr) {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: targetPr.number,
                body: 'Updated from issue #${{ github.event.issue.number }}'
              });
            }
