name: Convert Issue To Pull Request

on:
  issues:
    types:
      - opened

permissions:
  contents: write  # 授予写入权限
  pull-requests: write  # 授予创建 PR 的权限

jobs:
  convert-issue-to-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的 Git 历史

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create a new branch and commit a change
        run: |
          git checkout -b issue-${{ github.event.issue.number }}
          echo "Created from issue #${{ github.event.issue.number }}" > issue-${{ github.event.issue.number }}.txt
          git add issue-${{ github.event.issue.number }}.txt
          git commit -m "Create PR from issue #${{ github.event.issue.number }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Create PR from issue #${{ github.event.issue.number }}"
          title: 'Convert issue #${{ github.event.issue.number }} to PR'
          body: 'This PR is created from issue #${{ github.event.issue.number }}'
          branch: issue-${{ github.event.issue.number }}
          base: main
