name: Convert Issue To Pull Request

on:
  issues:
    types:
      - opened

jobs:
  convert-issue-to-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create a new branch and commit a change
        run: |
          git checkout -b issue-${{ github.event.issue.number }}
          echo "Created from issue #${{ github.event.issue.number }}" > issue-${{ github.event.issue.number }}.txt
          git add issue-${{ github.event.issue.number }}.txt
          git commit -m "Create PR from issue #${{ github.event.issue.number }}"
          git push origin issue-${{ github.event.issue.number }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Convert issue #${{ github.event.issue.number }} to PR'
          body: 'This PR is created from issue #${{ github.event.issue.number }}'
          branch: issue-${{ github.event.issue.number }}
          base: main
