name: Validate Application Proposal

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate-proposal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate proposal
        run: |
          if grep -q 'specific_pattern' path/to/proposal/file; then
            echo "Validation passed"
          else
            echo "Validation failed"
            exit 1
          fi
