name: Renew Cache

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  renew_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Renew cache
        run: |
          echo "Updating cache file..."
          echo "$(date)" > cache.txt
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add cache.txt
          git commit -m "Renew cache"
          git push
